name: Arch team official site
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
paginate: 5
github: https://github.com/Arch
urls:
    - text: rigofunc
      url: https://github.com/xyting
    - text: Arch
      url: https://github.com/Arch
