name: love.net team official site
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
paginate: 5
github: https://github.com/lovedotnet
urls:
    - text: github
      url: https://github.com/lovedotnet
    - text: email
      url: mailto:rigofunc@outlook.com
    - text: rigofunc
      url: https://github.com/xyting
    - text: lotosbin
      url: https://github.com/lotosbin
    - text: zcjin
      url: https://github.com/zicjin
    - text: yonglehou
      url: https://github.com/yonglehou
    - text: wangshifeng
      url: https://github.com/wangshifeng
    - text: linqtosql
      url: https://github.com/linqtosql
    - text: lilong
      url: https://github.com/lilong9298